package FindtheDifference;

/**
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.

 * Created by aoshen on 8/29/16.
 */
public class Solution {
    public char findTheDifference(String s, String t) {
        int[] counts = new int[26];

        for (int i = 0;i < s.length();++ i) {
            counts[s.charAt(i) - 'a'] ++;
        }

        for (int i = 0;i < t.length();++ i) {
            counts[t.charAt(i) - 'a'] --;
        }

        char result = 'a';

        for (int i = 0;i < 26;++ i) {
            if (counts[i] == -1) {
                result = (char) (result + i);
                break;
            }
        }

        return result;
    }
}
